# Generated by Django 3.2.25 on 2026-03-04 21:32

from django.db import migrations, models
from pgvector.django import VectorExtension
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='RAGInstructionChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_id', models.IntegerField(db_index=True)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('activity_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('last_indexed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='raginstructionchunkembedding',
            constraint=models.UniqueConstraint(fields=('instruction_id', 'chunk_index'), name='unique_instruction_chunk'),
        ),
    ]
