"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib  import Path
from decouple import config
from datetime import timedelta
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print(f"Django settings BASE_DIR: {BASE_DIR}")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
INSECURE_LOCAL_SECRET_KEY = "django-insecure-local-development-only"  # Fallback accepted only outside GCS deployment mode
SECRET_KEY = config("DJANGO_SECRET_KEY", default=INSECURE_LOCAL_SECRET_KEY).strip() or INSECURE_LOCAL_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = [
    'localhost', '127.0.0.1', "backend",
    "cognibot.org",            "www.cognibot.org", 
    "deployment.cognibot.org", "www.deployment.cognibot.org",
    "sandbox.cognibot.org",    "www.sandbox.cognibot.org",
    "sandbox2.cognibot.org",   "www.sandbox2.cognibot.org",
    "sandbox3.cognibot.org",   "www.sandbox3.cognibot.org",
    "10.0.2.2", # for android dev
]


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'chat_app',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'pgvector.django',   # enables pgvector extension support for Django
    'rag_vectorstore',   # custom RAG vectorstore app for creating/storing embeddings.
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'
CORS_ALLOW_ALL_ORIGINS = True  # For development only

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {'DEFAULT_AUTHENTICATION_CLASSES'  : ('rest_framework_simplejwt.authentication.JWTAuthentication', ),
                  'DEFAULT_PERMISSION_CLASSES'      : ('rest_framework.permissions.IsAuthenticated',                ),}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME"     : timedelta(days=5),
    "REFRESH_TOKEN_LIFETIME"    : timedelta(days=30),
    "ROTATE_REFRESH_TOKENS"     : True,
    "BLACKLIST_AFTER_ROTATION"  : False,
    "UPDATE_LAST_LOGIN"         : False,

    "ALGORITHM"     : "HS256",
    "SIGNING_KEY"   : SECRET_KEY,
    "VERIFYING_KEY" : "",
    "AUDIENCE"      : None,
    "ISSUER"        : None,
    "JSON_ENCODER"  : None,
    "JWK_URL"       : None,
    "LEEWAY"        : 0,

    "AUTH_HEADER_TYPES"         : ("Bearer",),
    "AUTH_HEADER_NAME"          : "HTTP_AUTHORIZATION",
    "USER_ID_FIELD"             : "id",
    "USER_ID_CLAIM"             : "user_id",
    "USER_AUTHENTICATION_RULE"  : "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM"  : "token_type",
    "TOKEN_USER_CLASS"  : "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME"         : timedelta(days=15),
    "SLIDING_TOKEN_REFRESH_LIFETIME" : timedelta(days=30),

    "TOKEN_OBTAIN_SERIALIZER"           : "rest_framework_simplejwt.serializers.MyTokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER"          : "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER"           : "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER"        : "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER"   : "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER"  : "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}

CORS_ALLOW_CREDENTIALS = True
WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'



# --------------------------------------------------------------------------------
# Channels (for consumers communicating with eachother)
# --------------------------------------------------------------------------------
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}

# --------------------------------------------------------------------------------
# Database Details (ALL pulled from the environment)
# --------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE'   : 'django.db.backends.postgresql',
        'NAME'     : config('POSTGRES_DB'),
        'USER'     : config('POSTGRES_USER'),
        'PASSWORD' : config('POSTGRES_PASSWORD'),
        'HOST'     : config('POSTGRES_HOST', default='db').strip() or 'db',
        'PORT'     : config('POSTGRES_PORT', default='5432').strip() or '5432',
    },
    'vector': {
        'ENGINE'   : 'django.db.backends.postgresql',
        'NAME'     : config('VECTOR_DB_NAME'),
        'USER'     : config('VECTOR_DB_USER'),
        'PASSWORD' : config('VECTOR_DB_PASSWORD'),
        'HOST'     : config('VECTOR_DB_HOST', default='db_vector').strip() or 'db_vector',
        'PORT'     : config('VECTOR_DB_PORT', default='5432').strip() or '5432',
    }
}

DATABASE_ROUTERS = [
    'backend.db_routers.VectorDBRouter',
]

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [{'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
                            {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',          },
                            {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',         },
                            {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',        },]
AUTH_PASSWORD_VALIDATORS = []

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
LANGUAGE_CODE   = 'en-us'
TIME_ZONE       = 'UTC'
USE_I18N        = True
USE_TZ          = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL       = '/static/'
STATICFILES_DIRS = [BASE_DIR / "chat_app/static",]
STATIC_ROOT      = BASE_DIR / "staticfiles"

# Media files (content generated by users of the app: audio recordings, etc.)
MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Session recording storage (local by default for development and Docker testing)
SESSION_AUDIO_STORAGE              = config("SESSION_AUDIO_STORAGE",              default="local"                   )  # "local" or "gcs"
SESSION_AUDIO_LOCAL_ROOT           = config("SESSION_AUDIO_LOCAL_ROOT",           default=str(MEDIA_ROOT)           )  # Durable local recording root
SESSION_AUDIO_TEMP_ROOT            = config("SESSION_AUDIO_TEMP_ROOT",            default="/tmp/cognibot_recordings")  # In-progress WAV directory
SESSION_AUDIO_GCS_BUCKET           = config("SESSION_AUDIO_GCS_BUCKET",           default=""                        )  # Private GCS bucket used in deployments
SESSION_AUDIO_OBJECT_PREFIX        = config("SESSION_AUDIO_OBJECT_PREFIX",        default="recordings"              )  # Object prefix within local storage or GCS
SESSION_AUDIO_PLAYBACK_URL_TTL_SEC = config("SESSION_AUDIO_PLAYBACK_URL_TTL_SEC", default=3_600, cast=int           )  # Playback URL lifetime

if (SESSION_AUDIO_STORAGE == "gcs") and (SECRET_KEY == INSECURE_LOCAL_SECRET_KEY):
    raise ImproperlyConfigured("DJANGO_SECRET_KEY must be configured before using deployed GCS audio storage")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD  = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL  = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL           = '/'


# --------------------------------------------------------------------------------
# Seeded user information from the private environment file
# --------------------------------------------------------------------------------
# Primary admin user
ADMIN_USERNAME_0 = config("ADMIN_USERNAME_0", default="")
ADMIN_PASSWORD_0 = config("ADMIN_PASSWORD_0", default="")

# Secondary admin user
ADMIN_USERNAME_1 = config("ADMIN_USERNAME_1", default="")
ADMIN_PASSWORD_1 = config("ADMIN_PASSWORD_1", default="")

# Protected demo data user
DEMO_USERNAME_0 = config("DEMO_USERNAME_0", default="")
DEMO_PASSWORD_0 = config("DEMO_PASSWORD_0", default="")

# Buddy robot user
BUDDY_USERNAME = config("BUDDY_USERNAME", default="")
BUDDY_PASSWORD = config("BUDDY_PASSWORD", default="")


# --------------------------------------------------------------------------------
# Optional seed datasets (safe create-if-missing behavior)
# --------------------------------------------------------------------------------
SEED_UI_SAMPLE_DATA       = config("SEED_UI_SAMPLE_DATA",       default=False, cast=bool)  # Random DB objects to demo the UI -- chats, reminders, activities, and RAG fixtures
SEED_ANALYZED_CHAT_DATA   = config("SEED_ANALYZED_CHAT_DATA",   default=False, cast=bool)  # Fixed text-only analyzed chat fixtures (used for testing `post_chat_analysis`)
SEED_TRANSCRIPT_CHAT_DATA = config("SEED_TRANSCRIPT_CHAT_DATA", default=False, cast=bool)  # Imported transcript, audio, and biomarker fixtures (from real recorded conversations)
