# Generated by Django 3.2.25 on 2026-02-09 00:37

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
from django.contrib.postgres.fields import ArrayField
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('Patient', 'patient'), ('Caregiver', 'caregiver'), ('Family', 'family'), ('Physician', 'physician'), ('Other', 'other')], max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('photographer', models.CharField(max_length=100)),
                ('photographer_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('locationStatus', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_account', to='chat_app.account')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientViewOverall', models.BooleanField(default=True)),
                ('patientCanSchedule', models.BooleanField(default=True)),
                ('taskType', models.CharField(choices=[('chat', 'Chat'), ('chattopic', 'ChatTopic'), ('chatimage', 'ChatImage')], default='chat', max_length=32)),
                ('taskSubtype', models.CharField(default='N/A', max_length=32)),
                ('modelChoice', models.CharField(choices=[('buddy', 'Buddy'), ('qt', 'QT')], default='buddy', max_length=32)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings_user', to='chat_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('daysOfWeek', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=7)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_user', to='chat_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RAGInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('description', models.TextField()),
                ('instruction_order', models.PositiveIntegerField(db_index=True, default=1)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rag_instructions', to='chat_app.activity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rag_instructions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.PositiveIntegerField(default=5)),
                ('auto_renew', models.BooleanField(default=True)),
                ('period', models.CharField(choices=[('N', 'None'), ('W', 'Weekly'), ('M', 'Monthly')], default='W', max_length=1)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('start_dow', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='chat_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('webapp', 'WebApp'), ('mobile', 'Mobile'), ('qtrobot', 'QTRobot'), ('buddyrobot', 'BuddyRobot'), ("demo", "Demo")], default='webapp', max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('end_ts', models.DateTimeField(blank=True, null=True)),
                ('audio_file', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('topics', models.CharField(blank=True, default="['No','Topics','Available']", max_length=255, null=True)),
                ('sentiment', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('taskType', models.CharField(blank=True, default='chat', max_length=255, null=True)),
                ('taskSubtype', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat_app.albumimage')),
                ('risk_level', models.CharField(blank=True, null=True, max_length=32, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')])),
                ('risk_quotes', ArrayField(models.CharField(max_length=255), null=True, blank=True)),
                ('risk_reason', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='chat_app.profile')),
            ],
            options={
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=32)),
                ('content', models.TextField()),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('start_ts', models.DateTimeField(blank=True, null=True)),
                ('end_ts', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_app.chatsession')),
            ],
            options={
                'ordering': ['-ts', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChatBiomarkerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(choices=[('alteredgrammar', 'AlteredGrammar'), ('anomia', 'Anomia'), ('pragmatic', 'Pragmatic'), ('pronunciation', 'Pronunciation'), ('prosody', 'Prosody'), ('turntaking', 'Turntaking'), ("perplexity", "Perplexity")], max_length=32)),
                ('score', models.FloatField()),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biomarker_scores', to='chat_app.chatsession')),
            ],
            options={
                'ordering': ['-ts', 'score_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.CharField(blank=True, choices=[('Full', 'full'), ('View', 'view')], default='full', max_length=100, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_access', to='chat_app.account')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_access', to='chat_app.profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='usersettings',
            constraint=models.UniqueConstraint(fields=('profile',), name='one_settings_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='raginstructions',
            constraint=models.UniqueConstraint(fields=('name', 'user', 'activity'), name='unique_rag_instruction_per_user_activity_name'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.UniqueConstraint(fields=('profile',), name='one_goal_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('profile',), name='unique_active_session_per_profile'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'ts'], name='chat_app_ch_session_1e0ad4_idx'),
        ),
    ]
