# Generated by Django 3.2.25 on 2026-03-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbiomarkerscore',
            options={'ordering': ['ts', 'score_type', 'id']},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['ts', 'id']},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='source',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='emotion',
            field=models.CharField(blank=True, default='N/A', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='llmVersion',
            field=models.CharField(default='phi3_finetuned', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='end_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='topics',
            field=models.CharField(blank=True, default="['N/A']", max_length=255, null=True),
        ),
    ]
