# Generated by Django 3.2.25 on 2026-03-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='source',
            field=models.CharField(choices=[('llm', 'LLM'), ('admin', 'Admin'), ('other', 'Other')], default='llm', max_length=32),
        ),
    ]
