"""
Shared text preprocessing for text-based biomarkers.
--------------------------------------------------------------------------------
`backend.chat_app.websocket.biomarkers.preprocessing.text_preprocessing`

Shared preprocessing for both offline and online feature extraction.

Returns the cleaned text, NLTK tokens, and POS tags. Each text biomarker
receives all three so we only tokenize and POS-tag once per utterance.
"""
import re, nltk, unicodedata
from typing import Iterable, List

# Keep only characters we expect NLTK + our grammar features to handle.
# NOTE: keep digits because we convert standalone numbers to words before tokenization.
_ALLOWED_TEXT_CHARS_RE = re.compile(r"[^a-z0-9\s\.\?\!,;:'\"-]")

# --------------------------------------------------------------------------------
# Remove IPA / phonetic symbols
# --------------------------------------------------------------------------------
def strip_unsupported_text_chars(text: str) -> str:
    """
    Remove characters outside the supported English-text preprocessing set.

    It also avoids NLTK syllable-tokenizer warnings from symbols outside
    its sonority hierarchy.
    """
    # Normalize common unicode punctuation first.
    text = text.translate(str.maketrans({
        "’": "'",
        "‘": "'",
        "“": '"',
        "”": '"',
        "–": "-",
        "—": "-",
        "\u00a0": " ",
    }))

    # Decompose accents when possible.
    # Example: café -> cafe
    text = unicodedata.normalize("NFKD", text)

    # Drop remaining non-ASCII characters (removes IPA symbols like ɝ and ɪ)
    text = text.encode("ascii", "ignore").decode("ascii")

    # Remove any remaining unsupported ASCII symbols.
    text = _ALLOWED_TEXT_CHARS_RE.sub(" ", text)

    # Clean spacing again after removals.
    return re.sub(r"\s+", " ", text).strip()

# --------------------------------------------------------------------------------
# Text Normalization
# --------------------------------------------------------------------------------
def normalize_text(text: str) -> str:
    """
    Standardize the raw utterance text for biomarker calculations.
    Steps:
      1. Lowercase
      2. Strip unsupported unicode / IPA characters
      3. Collapse repeated whitespace
      4. Strip leading/trailing whitespace
    """
    text = text.lower()
    text = strip_unsupported_text_chars(text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

# --------------------------------------------------------------------------------
# Convert NLTK contraction tokens to full words
# --------------------------------------------------------------------------------
def replace_contraction_tokens(tokens: Iterable[str]) -> List[str]:
    """
    NLTK tunrs contractions into these kinds of tokens with apostraphes included,
    we change some of the known ones to full words.

    TODO: There may be more to add that we haven't thought of...
    """
    # Mapping for tokens specifically generated by NLTK word_tokenize
    CONTRACTION_MAP = {
        "n't" : "not",
        "'re" : "are",
        "'ve" : "have",
        "'s"  : "is",
        "'ll" : "will",
        "'d"  : "would",
        "'m"  : "am",
        "wo"  : "will",  # NLTK splits  won't -> [wo,  n't]
        "ca"  : "can",   # NLTK splits  can't -> [ca,  n't]
        "sha" : "shall"  # NLTK splits shan't -> [sha, n't]
    }
    return [CONTRACTION_MAP.get(token, token) for token in tokens]

# ================================================================================
# NLTK Preprocessing
# ================================================================================
def preprocess(text: str):
    """
    Returns:
        cleaned  => normalized text
        tokens   => NLTK word_tokenize output
        pos_tags => NLTK pos_tag output
    """
    # 1. Lowercase + clean whitespace
    cleaned = normalize_text(text)
    if not cleaned: return "", [], []

    # 2. NLTK word_tokenize
    tokens = nltk.word_tokenize(cleaned)
    if not tokens: return cleaned, [], []

    # 3. NLTK pos_tag (returns list of (token, tag) tuples)
    tokens = replace_contraction_tokens(tokens)
    pos_tags = nltk.pos_tag(tokens)

    return cleaned, tokens, pos_tags
